version: '3.4'

services:
  apartmentbooking-api:
    image: ${DOCKER_REGISTRY-}apartmentbookingapi
    container_name: ApartmentBooking.Api
    build:
      context: .
      dockerfile: ApartmentBooking.Api/Dockerfile
    depends_on:
      - apartmentbooking-db

  apartmentbooking-db:
    image: postgres:latest
    container_name: ApartmentBooking.Db
    environment:
      - POSTGRES_DB=apartment_booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  apartmentbooking-idp:
    image: jboss/keycloak:latest
    container_name: ApartmentBooking.Identity
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/apartmentbooking-realm-export.json
    volumes:
      - ./.containers/identity:/opt/jboss/keycloak/standalone/data
      - ./.files/apartmentbooking-realm-export.json:/tmp/apartmentbooking-realm-export.json
    ports:
      - 18080:8080
